// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOJW0FJ68LnIRCVr0Q_b-lxn3hhBmMSoo',
    appId: '1:454722899170:web:6d4d6e4c457290542062bb',
    messagingSenderId: '454722899170',
    projectId: 'gas-app-e12b7',
    authDomain: 'gas-app-e12b7.firebaseapp.com',
    storageBucket: 'gas-app-e12b7.appspot.com',
    measurementId: 'G-SSGYCWLCLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKss1l-CrZTgOiTecA9XT4yLf9zxA9P0',
    appId: '1:454722899170:android:94af846a70d181202062bb',
    messagingSenderId: '454722899170',
    projectId: 'gas-app-e12b7',
    storageBucket: 'gas-app-e12b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtShvKurjYPy2RfiUbKkj-y1fN1gER6GE',
    appId: '1:454722899170:ios:e9204f390920ee682062bb',
    messagingSenderId: '454722899170',
    projectId: 'gas-app-e12b7',
    storageBucket: 'gas-app-e12b7.appspot.com',
    iosClientId: '454722899170-o6qmt31tp6s3056d6u6m87s9efl4u1v0.apps.googleusercontent.com',
    iosBundleId: 'com.gas.gas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtShvKurjYPy2RfiUbKkj-y1fN1gER6GE',
    appId: '1:454722899170:ios:e9204f390920ee682062bb',
    messagingSenderId: '454722899170',
    projectId: 'gas-app-e12b7',
    storageBucket: 'gas-app-e12b7.appspot.com',
    iosClientId: '454722899170-o6qmt31tp6s3056d6u6m87s9efl4u1v0.apps.googleusercontent.com',
    iosBundleId: 'com.gas.gas',
  );
}
